insert into public.site_settings (key, value) values
  ('site_url', 'spartacorepuestos.cl'),
  ('contact_email', 'contacto@spartacorepuestos.cl'),
  ('contact_phone', '+56 9 7554 8568'),
  ('contact_address', 'Longitudinal Sur 169, b, Chillán, Ñuble'),
  ('maps_url', 'https://maps.google.com'),
  ('store_hours_weekday', 'Lunes a Viernes: 9:00 a 13:00 y 15:00 a 18:00'),
  ('store_hours_saturday', 'Sábados: 9:00 a 14:00'),
  ('facebook_url', 'https://facebook.com/yourpage'),
  ('instagram_url', 'https://instagram.com/spartacorepuestos'),
  ('tiktok_url', 'https://tiktok.com/@yourpage'),
  ('whatsapp_url', 'https://wa.me/569975548568'),
  ('transfer_company_name', 'Importadora y Distribuidora CodSpace Ltda.'),
  ('transfer_company_rut', '76.123.456-K'),
  ('transfer_bank_name', 'Banco de Chile'),
  ('transfer_account_type', 'Cuenta Corriente'),
  ('transfer_account_number', '12-34567-89'),
  ('transfer_email', 'pagos@codspace.cl'),
  ('smtp_host', ''),
  ('smtp_port', '587'),
  ('smtp_user', ''),
  ('smtp_password', ''),
  ('smtp_from', '')
on conflict (key) do nothing;
